### PR TITLE
Fix root value range for RRCEstablishmentCause

### PR DESCRIPTION
**Pull request by YoheiKonno**
The root value range of RRCEstablishmentCause is 0 to 9.

`notAvailable(10)` is extended value.

### CODE REVIEW

**Review by free5gc-org — CHANGES_REQUESTED** [review]
`RRCEstablishmentCausePresentNotAvailable aper.Enumerated = 10` can be removed.

**Comment by YoheiKonno** [comment]
1. `RRCEstablishmentCausePresentNotAvailable aper.Enumerated = 10` is necessary because extended value is following root values. For example, NotAvailable's actual value (0) is calculated by this 10 - (`valueUB:9` + 1).
2. updated

**Review by free5gc-org — APPROVED** [review]

**Comment by free5gc-org** [comment]
@YoheiKonno 
Which spec defines NotAvailable's actual value is 0? I can't find its definition in TS 38.413.
If NotAvailable's actual value is 0, does it conflict with emergency cause (0)?

**Comment by YoheiKonno** [comment]
@free5gc-org 
It's not 3GPP spec, but ASN.1 PER spec, i.e. ITU-T X691.
On "14 Encoding the enumerated type  -  14.1", T-REX-X691
>  The extension additions (which are always defined in ascending order) shall be assigned an enumeration index starting with zero for the first enumeration, one for the second, and so on up to the last enumeration in the extension additions. 

So, "emergency" is the first of the root values and "NotAvailable" is the first of  the extensional values.

**Comment by YoheiKonno** [comment]
```
RRCEstablishmentCause ::= ENUMERATED {
  emergency,
  //  snip
  ...,    // this indicates the start of extension part
  notAvailable
}
```

**Comment by free5gc-org** [comment]
@YoheiKonno 

From ASN.1 T-REC-X680:
image

Follow case A of 19.6, we think notAvailable's value should be (10):
image1

**Comment by YoheiKonno** [comment]
Yes, notAvailable's value is 10 in applicaiton view.

"actual value is 0" was not accurate.
In ASN.1 PER (Packed Encoding Rule) view, the encoded value of EnumeratedType into PER binary is index value of enumerated items, and notAvailable's index value in RRCEstablishmentCause's extentional values is "0".

You can check it as following:
1. change `test/ngapTestpacket/build.go` as
```go
func BuildInitialUEMessage(ranUeNgapID int64, nasPdu []byte, fiveGSTmsi string) (pdu ngapType.NGAPPDU) {
// snip
	rRCEstablishmentCause := ie.Value.RRCEstablishmentCause
	// rRCEstablishmentCause.Value = ngapType.RRCEstablishmentCausePresentMtAccess
	rRCEstablishmentCause.Value = ngapType.RRCEstablishmentCausePresentNotAvailable
// snip
}
```

2. run `test.sh -o TestRegistration`

3. inspect the packet capture by WireShark. It should be like 
image

- notAvailable is 10 in applicaiton view.
- PER encoded value is `0x80`. It represents that the value is extensional value since MSB is 1 and index value is 0.


I think if NamedNumber is used for some EnumeratedType like
```
RRCEstablishmentCause ::= ENUMERATED {
  emergency (5),
  ...,
  notAvailable(10)
}
```
, PER encoder should encode emergency to 0 without extention flag and PER decoder should treat encoded value 0 without extension flag as emergency and return 5 to the application that called the PER decoder. And if the encoded value is 0 with extension flag, the PER decoder should treat is as notAvailable and return 10 to the application.

**Comment by free5gc-org** [comment]
@YoheiKonno 

Could you specify each bit meaning for enumerated type? It seems including 2 encoding ways.

**Comment by YoheiKonno** [comment]
It is defined in 14.3 of T-REX-X.691 since RRCEstablishmentCause definition has an extension marker.

image

Bits other than MSB i.e. a bit-field of length one, is encoded either as a constrained whole number or a normally small non-negative whole number.

image

**Comment by free5gc-org** [comment]
Thanks for the clarification!

**Pull request merged**
